apiVersion: v1
kind: Service
metadata:
  name: {{ include "status-tester.fullname" . }}
  labels:
    {{- include "status-tester.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30002
  selector:
    {{- include "status-tester.selectorLabels" . | nindent 4 }}
